---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!'

---
version: 2
plan: MARS-ROCKET

plan-permissions:
  - roles: logged-in
    permissions: 
    - view
    - edit
    - build
